import Image from "next/image";
import logo from "src/public/icook-logo.png";


export default function Head() {
  return (
    <>
      <title>iCook</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/png" href={logo} />

    </>
  );
}
