export default function Head() {
  return (
    <>
<<<<<<< HEAD:src/app/head.jsx
      <title>iCook</title>
=======
      <title>ICook. Find your perfect recipe.</title>
>>>>>>> daria:src/app/head.js
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
